name: Build and Release Go Binary

on:
  push:
    tags:
      - 'v20[0-9][0-9]-[0-1][0-9]-[0-3][0-9][a-z]'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'

      - name: Build binary
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o bin/musannif-${{ matrix.goos }}-${{ matrix.goarch }} cmd/musannif/main.go

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          file: ./bin/musannif-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_name: musannif-${{ matrix.goos }}-${{ matrix.goarch }}
          overwrite: true
